server:
  port: 8009
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sound-good
    username: postgres
    password: Harold123
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          charset_name: UTF-8
          import_files: scripts/documentType.sql, scripts/genderType.sql, scripts/user.sql, scripts/specialities.sql, scripts/medicine.sql, scripts/hearing_losses.sql, scripts/doctors.sql, scripts/patients.sql, scripts/doctor_speciality.sql, scripts/person_hearing_loss.sql

security:
  jwt:
    secret: GamesFull123
    issuer: Main
    ttlMillis: 3600000