server:
  port: 8155
  address: 0.0.0.0
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yorksanc@gmail.com
    password: lfrwjavbmczhflsd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:postgresql://3.141.52.158:5432/soundgood
    username: postgres
    password: Admin.$12
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          charset_name: UTF-8
          import_files: scripts/documentType.sql, scripts/genderType.sql, scripts/user.sql, scripts/specialities.sql, scripts/medicine.sql, scripts/hearing_losses.sql, scripts/doctors.sql, scripts/patients.sql, scripts/doctor_speciality.sql, scripts/person_hearing_loss.sql, scripts/emailTemplate.sql
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
security:
  jwt:
    secret: GamesFull123
    issuer: Main
    ttlMillis: 3600000
settings:
  url:
    front: https://front-sound-good.vercel.app/